### PR TITLE
Non-invasive Targeting Hooks

### PR DESCRIPTION
**Pull request by Kovak**
Hi so I thought about this today and what about something like this instead?

With this method none of the mods have to have a hard dependency on each other but things will just work out. You can see the way another mod would use the api here:

https://github.com/ChaosBuffalo/TargetingAPI/blob/master/src/main/java/com/chaosbuffalo/targeting_api/integration/Integrations.java#L18

### CODE REVIEW

**Comment by Lycanite** [comment]
The problem with this way is that it's only checking for the ENEMY type so it would need to be for AITargetAttack and maybe AITargetAvoid too, but there are also cases where some mobs fight each other such as Alpha Jousts.
Would the LivingSetAttackTargetEvent not also do the job for protecting friendly entities from being targeted too? I currently use this event for the canBeTargetedBy() method to stop things like bosses being targeted or for Tremors to be ignored by Withers, etc.

**Comment by Kovak** [comment]
AITargetAttack already works properly for sure since these callbacks just provide some additional filtering in the isSuitableTarget that only applies if isValidTarget has returned true. If isValidTarget determines the target to not be valid, none of the additional filterings will be called. Is there a case at the moment where isSuitableTarget is used for non-hostile targeting, when I looked I didn't notice any occurences? It won't stop jousts from fighting, and it doesn't interrupt any other lycanites targeting logic, it just allows other mods to enable additional callbacks that will also say 'this is not a target'

I must admit I haven't looked precisely into the avoid behavior (although it seems to be functioning properly), but really given that the main goal of the overrides at the moment is to ensure players, player pets, and various npcs from other mods work together, the attack behaviors are noticeable during gameplay but the avoid ones less so. 

For a little more background as to why I am doing all this:

My real end goal is to have Lycanites work properly with my mod, but also with Minecolonies. Minecolonies introduces an EntityCitizen class that largely behaves like a 'friendly' mob but also actually has a 'guard' version of the entity that is capable of participating in pvp. I want to make sure that player's pets are able to attack the guards when the guards are able to attack them, but not when the guards are friendly, and also that the guards properly defend against the creatures in Minecolonies.

Minecolonies presents a unique problem for the targeting system because they have 6 subvarients of the same EntityCitizen that can't be distinguished by class, just state on the entity itself. This means that only some code that has knowledge of the internal workings of Minecolonies can judge the hostile status of an EntityCitizen. So I came up with the callback registration approach.

The Minecolonies callback looks like this, and really nothing short of being able to call those permission functions on the entity would enable us to properly determine whether or not a pet should attack a guard:

```java
private static void setupTargeting(){
        BiFunction<Entity, Entity, Boolean> friendlyWrapper = (caster, target) -> {
            if (caster instanceof EntityCitizen && target instanceof EntityPlayer){
                EntityCitizen worker = (EntityCitizen) caster;
                // Guards are not friends with players they have permission to attack
                if (worker.getColonyJob() != null && worker.getColonyJob() instanceof JobGuard){
                    if (!(worker.getColony() != null && worker.getColony().getPermissions().hasPermission(
                            (EntityPlayer) target, Action.GUARDS_ATTACK))){
                        return true;
                    }
                } else {
                    // all other citizens are friends with players
                    return true;
                }
            }
            // We need the reverse targeting of above too.
            if (caster instanceof EntityPlayer && target instanceof EntityCitizen){
                EntityCitizen worker = (EntityCitizen) target;
                if (worker.getColonyJob() != null && worker.getColonyJob() instanceof JobGuard){
                    if (!(worker.getColony() != null && worker.getColony().getPermissions().hasPermission(
                            (EntityPlayer) caster, Action.GUARDS_ATTACK))){
                        return true;
                    }
                } else {
                    // all other citizens are friends with players
                    return true;
                }
            }
            if (caster instanceof EntityCitizen && target instanceof EntityCitizen){
                EntityCitizen worker = (EntityCitizen) caster;
                EntityCitizen worker_target = (EntityCitizen) caster;
                if (worker.getColonyJob() != null && worker.getColonyJob() instanceof JobGuard){
                    if (worker.getColony().equals(worker_target.getColony())){
                        return true;
                    }
                } else {
                    return true;
                }

            }
            return false;
        };
        Targeting.registerFriendlyCallback(friendlyWrapper);
    }
```

The full integration on the Minecolonies side looks like this:

https://github.com/ChaosBuffalo/minecolonies/compare/version/1.12...ChaosBuffalo:1.12-targeting-fixes

**Comment by Lycanite** [comment]
Ok so there's no harm in integrating this then, but it would need to be moved to isValidTarget() in AITargetAttack and AITargetOwnerThreats isSuitableTarget() is for generic checks such as if the entity is alive, not a creative player, etc and is used by all targeting AI such as AITargetMaster which is used by Jousts to target Alpha Jousts for herding or AITargetParent where child mobs find the nearest parent mob. If isSuitableTarget() is checking for enemies it could break these as they are checking for allies.
All targeting AI extends AITarget but override isValidTarget() so putting it there would be a better option.

What I'll do is reorganise all these checks as they're a bit messy at the moment, then I'll integrate this into any attack AI checks.

**Comment by Lycanite** [comment]
What I should do is rename these methods, perhaps changing isSuitableTarget to isEntityTargetable or something to outline that it's a generic not dead, etc test to be used by all types of targeting.

**Comment by Lycanite** [comment]
I've integrated the callback feature so can close this now.

**Pull request closed without merging**
