### PR TITLE
Fixes Idle Glitch

### PR DESCRIPTION
**Pull request by LakMoore**
This patch fixes the idling mobs glitching as discussed in issue #165 

Also, adds some debugging lines to the mobs, which are shown when the bounding boxes are enabled (easy to remove if you don't like).

Sorry it is only for 1.7.10! :-/

Hope you can use this patch.

### CODE REVIEW

**Comment by LakMoore** [comment]
Don't use this!  Although it fixes the glitches from AILookIdle it also breaks AIWander!

Will keep looking!

**Comment by Lycanite** [comment]
Thanks for looking into it for me! If you fix it I'll port the fix to 1.10 too! :)

**Comment by LakMoore** [comment]
Found it... finally!
This took me so long to figure out.  I was totally looking in the wrong place.  Anyway, I learnt a lot doing it too, so all is good!

**Comment by Lycanite** [comment]
Wow thanks for fixing this! I'll get a new 1.7.10 build out with this asap, I'll also look into porting this into the 1.10 build too!

**Pull request merged**
