### PR TITLE
Gradlify LycaniteMobs

### LINKED ISSUE #193: [Src] Include Gradle, Rename Package Name
Currently plain java environment is used with no build system. Although there is nothing wrong with having that, the scope and size of the project has gotten to a point where gradle should be used. Forge provides ForgeGradle for managing forge version, mcmod.info updating and gradle allows running unit tests.

Edit: If you do consider it let me know i can open a PR with the setup

### PR DESCRIPTION
**Pull request by kinggoesgaming**
Very much WIP.

closes #193

### CODE REVIEW

**Comment by xlxAciDxlx** [comment]
Assuming @Lycanite actually wants to use this to do release builds in the future, shouldn't the *build.gradle* roughly match the Forge MDK file? Other than that, it looks good 👍

**Comment by kinggoesgaming** [comment]
MCP site is down so I can't do stuff on it. waiting for it to go up. i will split the project up into gradle submodules too

**Comment by kinggoesgaming** [comment]
@Lycanite noooo didnt i say this was WIP????

**Comment by Lycanite** [comment]
Ah crap, my bad, should I revert it, I'm not using the branch atm anyway?

**Comment by kinggoesgaming** [comment]
See #199 comments

**Pull request merged**
