### PR TITLE
[AI] Team Mates and Targeting

### LINKED ISSUE #250: [Pets] Aggressive Pets PVP
Pets set to aggressive ignore the pvp flag and attack other players.

### PR DESCRIPTION
**Pull request by Kovak**
This fixes #250 , among other things.

I notice you don't have any dependencies at the moment so I don't know how you feel about those, but this PR grew out of solving a problem I had trying to integrate lycanites in a nice way for my players with the other mods we use.

I have a custom rpg combat mod focused around group combat. The summons in lycanites really fit in thematically, but they pretty much attack all players other than their owner right now which makes them a real pain for people trying to play together. This partly comes down to the fact that Lycanites doesn't respect the built in team feature when it comes to hostile targeting, only friendly targeting, but the problem runs a little deeper than that: ultimately various mods need a way to communicate to tell each other about the role of various entities (for instance we do not want our hostile spells and abilities to run on the fairies as they are beneficial mobs and we make heavy use of aoes that would otherwise wipe them out and the players were sad). Up until now, we've been doing this ad-hoc in our custom mod side of things, but fixing the pets in lycanites required hooking into the AI code you run. So I started splitting out the targeting bits and created this targeting api: https://github.com/ChaosBuffalo/TargetingAPI

It currently supports correctly identifying teammates, their mounts, and their pets, declaring certain mob classes as friendly or enemies, registering certain mobs as player friendly, and registering custom callbacks to perform mod specific logic. We don't quite need all of these features and actually the integration with lycanites is very minimal, but it will also allow us to hook into mods like Minecolonies and ensure their guard NPCs also treat the mobs in lycanites correctly. We've been running the base targeting code for a few years now, and have already been testing the lycanites integration specifically for a few weeks now.

I understand if you're not interested in taking on dependencies, but I thought I'd share because it seems like an area in need of a little love to really make the experience as polished as possible.

### CODE REVIEW

**Comment by Lycanite** [comment]
I'd rather avoid the use of dependencies, mostly due to Minecraft update concerns, however I'm happy to look into the team based targeting more, a lot of that logic was written a long time ago and could do with being overhauled.

**Comment by Kovak** [comment]
I would recommend handling at the least teammates, IEntityOwnables, the passenger/mount system, and providing some type of configurable white list or an api to add to one so that other mods that introduce player friendly NPCs dont have their villagers and such murdered by the pets. Feel free to lift the logic necessary from: https://github.com/ChaosBuffalo/TargetingAPI/blob/master/src/main/java/com/chaosbuffalo/targeting_api/Targeting.java

**Comment by Lycanite** [comment]
Sounds like a plan and thanks for the info!
So what I'll do is:
- Rely heavily on isOnSameTeam() for targeting.
- Create a string based faction name for groups like fire mobs instead of using interfaces. Perhaps later extend this into a proper faction system where vanilla or modded entities can be added to factions via configs.
- Add mount and IEntityOwnable checks to isOnSameTeam(). 
- The canAttackTarget() method should do simple boss checks, etc before referring to isOnSameTeam().
- The hostile towards player check should check if the target entity is able to attack the player not just if it's hostile in general and not on the same team. 
- Add a config entry where comma separated player friendly entity ids can be added in addition to similar lists where needed.

**Comment by Lycanite** [comment]
I've created an issue for this: https://github.com/Lycanite/LycanitesMobs/issues/389

**Pull request closed without merging**
